### ISSUE TITLE
The Chrome Extension should work for Teams

### ISSUE THREAD

**Issue by JodieM** [gyazo/gyazo-browser-extension#155]
I have Gyazo for Teams. I also installed the extension. I took a few screen shots and wanted to see my history. It had saved them in Gyazo not Gyazo for Teams. I could not log into Gyazo because it said I was already logged into Gyazo for Teams. The images taken with the extension were not on my Teams site.

**Comment by pastak** [comment]
@JodieM Thank you for using Gyazo for Teams! :smile: 

We understand needs for Extension with Teams.

We have to develop API with Gyazo for Teams before provide Gyazo Extension for Teams.

Gyazo developer team is working now. Please wait for it.
