### ISSUE TITLE
Chrome WebStore User Data Policy

### ISSUE THREAD

**Issue by pastak** [gyazo/gyazo-browser-extension#167]
Google announced User Data Policy ( https://developer.chrome.com/webstore/program_policies#userdata )

This extension gets and sends screen-capture and basic infomation (URL and title) of webpage user visits.

I think this extension is required "Privacy Policy Requirements" so we should add private policy page ( https://gyazo.com/doc/privacy ) link to Chrome Extension Webstore's page and inline install page.  

FAQ: https://developer.chrome.com/webstore/user_data

**Comment by rakusai** [comment]
> we should add private policy page

Completely agree. Please do it!
