### ISSUE TITLE
It contains Gyazo tools popover in the image captured by "Page" tool

### ISSUE THREAD

**Issue by hiroshi** [gyazo/gyazo-browser-extension#212]
I'm not sure, but I suspect that it have happened since release 2.6.0.

<a href="https://gyazo.com/736af77c3f0c710d2edf3b2bf035fa22"><img src="https://i.gyazo.com/736af77c3f0c710d2edf3b2bf035fa22.png" alt="https://gyazo.com/736af77c3f0c710d2edf3b2bf035fa22" width="1178"/></a>

**Comment by hiroshi** [comment]
With [v2.6.1](https://github.com/gyazo/gyazo-browser-extension/releases/tag/v2.6.1), the issue seems to be fixed for me. Thanks.
<a href="https://gyazo.com/417cff872a376d8d1d48c1005cba762e"><img src="https://i.gyazo.com/417cff872a376d8d1d48c1005cba762e.png" alt="https://gyazo.com/417cff872a376d8d1d48c1005cba762e" width="1192"/></a>

For the record, which commit or PR fixed this issue?

**Comment by pastak** [comment]
It is fixed by https://github.com/gyazo/gyazo-browser-extension/commit/def3ea864722b872606ab2540b721c8e0fba0dca
