### ISSUE TITLE
「範囲選択」でキャプチャしたあと右クリックでコンテキストメニューが表示されない

### ISSUE THREAD

**Issue by yuiseki** [gyazo/gyazo-browser-extension#276]
## 望んでいた挙動
最初に「範囲選択」でキャプチャしてアップロード後にもう一度「範囲選択」でキャプチャしてアップロードしたかった

## 実際に発生した挙動
最初に「範囲選択」でキャプチャしてアップロードすると、リロードするまで右クリックができなくなってしまった

**Comment by hiroshi** [comment]
ほんとだ

**Comment by pastak** [comment]
あんまり気にしてないので、言語はどっちでも良いです

**Comment by hiroshi** [comment]
> あんまり気にしてないので、言語はどっちでも良いです（英語を頑張って調べたり書いたりできないとissueを書けないという場所ではないということは明確な立場としておきたい）

日本語読めないユーザーが過去の issue みたときの困り具合を懸念してましたが、たしかに日本人のユーザーも多いので日本語でも issue 書いてよいという雰囲気のほうがよいですね。
その他の言語でも自動翻訳すればなんとかなるか...

**Comment by yuiseki** [comment]
とりあえず忘れないうちにと思って雑にIssue作ってしまいました。すみません。
Issueテンプレートを用意してもらえるとありがたいです。
