### ISSUE TITLE
Publish your extension to Microsoft Edge Addons website

### ISSUE THREAD

**Issue by nagachaitanyalokam** [gyazo/gyazo-browser-extension#280]
Microsoft Edge is the second most used browser on the web, making the browsing experience more flexible, offering many more services for users and optimized for Windows devices.

Microsoft Edge supports Chromium extensions, and you can publish your extensions to Microsoft Edge Add-ons website with minimal code changes. Find out more [here](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/port-chrome-extension).

If you have any more queries about porting Chrome extension to Microsoft Edge or anything else, you can contact the relevant teams whose links are given [here](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/contact-extensions-team). 

Let me know if this was helpful. I am happy to help you with more details.

**Comment by pastak** [comment]
@nagachaitanyalokam Thanks for letting us know. We have kept publishing extension for legacy Edge but last Friday we have  published the extension for current version of Edge. It is waiting for review by Edge addons website.

**Comment by pastak** [comment]
It is accepted and published https://microsoftedge.microsoft.com/addons/detail/gyazo/bcboggmjkglcipefacieelammmdddcnp
